spring.application.name=medicina-service
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/medicina_service_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Laphroaig10
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5673
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

logging.level.com.centro_cirurgico_service=DEBUG

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method